version: 2
updates:
  # Root package dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "anadi45"
    assignees:
      - "anadi45"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Create package dependencies
  - package-ecosystem: "npm"
    directory: "/create-package"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    reviewers:
      - "anadi45"
    assignees:
      - "anadi45"
    commit-message:
      prefix: "deps(cli)"
      prefix-development: "deps-dev(cli)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "anadi45"
    assignees:
      - "anadi45"
    commit-message:
      prefix: "ci"
      include: "scope"
