version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: nest-server-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: npx nx serve server --host 0.0.0.0
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    container_name: react-client-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - node_modules:/app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    command: npx nx serve client --host 0.0.0.0
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
